### ISSUE TITLE
Text and icons not showing up in some instances

### ISSUE THREAD

**Issue by Kemprist** [MaximumADHD/Roblox-Studio-Mod-Manager#137] opened 2022-08-23 13:52 UTC
![image](https://user-images.githubusercontent.com/52800696/186175861-45208153-5966-4a32-a650-db39b9710e81.png)
![image](https://user-images.githubusercontent.com/52800696/186175971-60743fab-7cf8-4a0b-8e6b-23eeb97981b4.png)

**Comment by randomizednum** [comment] 2022-08-25 11:38
Duplicate of #135.
Why has the Studio Mod Manager been so unstable for the past few months? Is it Roblox making too many changes?

**Comment by MaximumADHD** [comment] 2022-08-26 00:42
Closing for duplicate.
This should be fixed in the latest release though.

**Closed by MaximumADHD** 2022-08-26 00:42 UTC
